# Generated by Django 2.1.15 on 2020-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('in_stock_quantity', models.IntegerField()),
            ],
        ),
    ]
