# Generated by Django 2.1.15 on 2020-08-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prezola', '0004_order_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prezola.Customer'),
        ),
    ]
