# Generated by Django 3.0.8 on 2020-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prezola', '0005_orderlineitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
