# Generated by Django 3.0.8 on 2020-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prezola', '0006_orderlineitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity_purchased',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
